GRAFANA_ADMIN_PASSWORD: ENC[AES256_GCM,data:9aiaK8U3LFVQhOpGhsh6hx7M1oNLw5ITXm1RjYZ/wJFIn5HsGGb/sHzlEL5THUYLqct4CcGUDiyU5izf,iv:6Fl87lAXcpcNB+Je+Q9UPlRWy/ypNgHFbK8OsRSBkRs=,tag:VtHYWlTcZLEaAgq8yFL/hA==,type:str]
dsp25-ssh: ENC[AES256_GCM,data:uayqUVTq4vpDDBS18yhO4g/ORxJd5Y7fCjmcOLkV/M0PieCkzjoQH5Ei+gicyRmPGA/BFEwzLelrDPbOMwQDpX06z3ps8/j/CSkiqU5WReNLDOKz419J4TM7ATx4nYAqmVL1k6sQaW98C3g2ITsJtFDwNjKr78ZJxm52SvAwpw8GxkbDGsO4,iv:XP918ersfRlvBML35rF/QdcibKCL+xRJn14I2yMkrrg=,tag:R/kXxPzTJcRe6/1XoZ8/8w==,type:str]
sops:
    age:
        - recipient: age1pcsgd5f5yefxk9667j40hsr8ereky6ufxhmda5dh0fzkajpzf5as9lcw36
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBwdHFoVFBKRjE4eklPVmwv
            bXlBOHk0SnFrRThDZmwzVUdja2Zkd0prc25ZCld4MG4vL3ljNlZTWWJPN2JyTy9y
            SDZ0VTRJa0tveC9OUUx2NGphcjhFOVEKLS0tIEpvSHRqR1U5YmxIRTRzZGhzc3pt
            NThXamtrdWdFWksvSzdiaWdhc2w0TTgKq+PgT/nBRFRcye+BPwmXuwJ1fulSTWRN
            jdLX8LQgHUGjNR/XDCHKF+lm7FOvs21HMf3YMW7f4NeEw7FCyfuNLQ==
            -----END AGE ENCRYPTED FILE-----
        - recipient: age1cag8j93g8jjw860fwecrcl4qvvmk7k9e00puehxacy6dl55ye5eqsg7h7a
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhcTRBbU13OE9MaDVJckY2
            OEZ6VTNJRjVaemxDTjlVL2RSMmNFdkJsSkdBCjZiV1Zad1htRE9Zc2pXak5YMjlj
            OUZRUWNuM01oK2VyNDlqZHlDcFVkYW8KLS0tIFIweFpZTFkrTXI5NVNRdlorSEE0
            U1NlVll0VU1RcTZseWdmcjlBNlIwYTQKh8VYyUp4sfePBq2bEm0FN2M/jNQiN1Kd
            U5UilM40AN+FStO56DEx/Ll7huygtUp0oLKW4aToQbj+Bqkb98RPTQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-24T22:05:00Z"
    mac: ENC[AES256_GCM,data:Gnkhtizp7JYaknqzsCGjNr988OS24F1qlwhmuqjTP6seB/0B/GbrAdZsC7D0RXvs5Vv65e/p383KnTYhU4UyOcz/4D+K431dkwi45Xig6mwrfK58P4YdjDfBL99d3dYb8523boYUN8Bp351wwvFjxkJ8cTWtefrFmfWAgXXF0gM=,iv:R3808V3wQlNwGlKwFjihdw2dFj0/S3aWd5EYMKGAsNQ=,tag:0FB7Q7lIHtLXshZHAfiXCg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
